inventory_pbp/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main
from main.views import show_main, create_product, show_xml
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register #sesuaikan dengan nama fungsi yang dibuat
from main.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from main.views import logout_user
from main.views import add_amount
from main.views import remove_amount
from main.views import delete_product
from main.views import edit_product
from main.views import get_product_json
from main.views import create_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_amount/<int:id>/', add_amount, name='add_amount'),
    path('remove_amount/<int:id>/', remove_amount, name='remove_amount'),
    path('delete_product/<int:id>/', delete_product, name='delete_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', create_ajax, name='create_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    product_name = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.CharField(max_length=20)  
    description = models.TextField()
    brand = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["product_name", "amount", "price", "description", "brand"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.db.models import Sum
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import json
@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    total_amount = items.count()
    jumlah_item = total_amount if total_amount is not None else 0 

    nama_mahasiswa = "Kezia Natalia Theodora N."
    kelas = "PBP C"

    context = {
        'nama_mahasiswa': nama_mahasiswa,
        'kelas': kelas,
        'jumlah_item' : jumlah_item,
        'items': items,
        'last_login': request.COOKIES['last_login'],
        'name': request.user.username,
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST, request.FILES)

    if form.is_valid():
        product = form.save(commit=False)
        product.user = request.user
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_amount(request, id):
    item = get_object_or_404(Item, pk=id)

    if request.method == 'GET':
        item.amount += 1
        item.save()
        messages.success(request, 'Jumlah Item Bertambah 1.')
        return redirect('main:show_main')

    return redirect('main:show_main')

def remove_amount(request, id):
    item = get_object_or_404(Item, pk=id)

    if request.method == 'GET':
        if item.amount > 0:
            item.amount -= 1
            item.save()
            messages.success(request, 'Jumlah Item Berkurang 1.')
        if item.amount == 0:
                item.delete()
        return redirect('main:show_main')

    return redirect('main:show_main')

def delete_product(request, id):
    item = get_object_or_404(Item, pk=id)

    if request.method == 'GET':
        item.delete()
        messages.success(request, 'Produk berhasil dihapus.')
        return redirect('main:show_main')

    return redirect('main:show_main')

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Item.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

...
@csrf_exempt
def create_ajax(request):
    print(request.POST)
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        print(product)

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block meta %}
    <title>Add New Product</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }

    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .form-container {
        background-color: rgba(255, 253, 230, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        max-width: 600px; /* Adjust the width as needed */
        width: 100%;
    }

    .form-container h1 {
        text-align: center;
        margin-bottom: 20px;
        color: #5d2a08;
    }

    form {
        margin-top: 20px;
    }

    table {
        width: 100%;
    }

    table td {
        padding: 10px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .btn {
        background-color: #5d2a08;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
        font-size: 16px;
    }

    .btn:hover {
        background-color: #c38b60;
    }
</style>

<div class="container">
    <div class="form-container">
        <h1>Add New Product</h1>

        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input class="btn" type="submit" value="Add Product" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
{% endblock content %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% block meta %}
    <title>Edit Product</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }

    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .form-container {
        background-color: rgba(255, 253, 230, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        max-width: 600px; /* Adjust the width as needed */
        width: 100%;
    }

    .form-container h1 {
        text-align: center;
        margin-bottom: 20px;
        color: #5d2a08;
    }

    form {
        margin-top: 20px;
    }

    table {
        width: 100%;
    }

    table td {
        padding: 10px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .btn {
        background-color: #5d2a08;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
        font-size: 16px;
    }

    .btn:hover {
        background-color: #c38b60;
    }
</style>

<div class="container">
    <div class="form-container">
        <h1>Edit Product</h1>

        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input class="btn" type="submit" value="Edit Product" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    }

    .login-container {
    color :#5d2a08;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    }

    .login-box {
        background-color: rgba(255, 253, 230, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        max-width: 400px; 
        margin: auto; 
    }

    .login-box h1 {
        text-align: center;
        margin-bottom: 20px;
    }

    .login-form td {
        padding: 10px;
    }

    .form-control {
        width: calc(100% - 20px); 
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .login_btn {
        background-color: #5d2a08;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
        font-size: 16px;
    }

    .login_btn:hover {
        background-color: #c38b60;
    }

    .login-form {
        margin-bottom: 20px;
    }

    .login-box p {
        margin-top: 20px;
        text-align: center;
    }


    .login-box h1 {
        text-align: center;
    }

    .login-form {
        margin-top: 20px;
    }

    .login-form table {
        width: 100%;
    }

    .login-form td {
        padding: 10px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
</style>

<div class="login-container">
    <div class="login-box">
        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table class="login-form">
                <tr>
                    <td>Username:</td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>

                <tr>
                    <td>Password:</td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
  <!DOCTYPE html>
  <html>
  <head>
    <title>Welcome To ChocoStock</title>
    <style>
      h1 {
        font-size: 36px;
        color: #000000; 
        text-align: left; 
      }

      h5 {
        font-size: 22px;
        color: #000000;
        text-align: center;
      }

      .name {
        font-size: 18px;
        color: #000000;
        text-align: center;
      }

      table {
        border-collapse: collapse;
    }

    th, td {
        text-align: center;
        color: #000000;
        border: 1px solid #000;
    }
      .attribute {
        font-weight: bold;
      }

  body{
    background-color: bisque;
  }
    .header {
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
    color: #ffffff; 
    text-align: center;
    padding: 100px 0; 
}

  .header h1 {
      font-size: 36px;
      text-align: center;
      margin: 0;
  }

  .container h3{
    font-size: 24px;
    text-align: center;
    padding: 20;
    margin-bottom: 10px;
  }
  
  .card{
    background-color: beige;
    width: 400px;
    height: 400px;
  }
  
    </style>
  </head>
  <body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Kezia Natalia T. N.</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <a href="{% url 'main:logout' %}">
                <button class="btn btn-outline-success" type="submit">Logout</button>
            </a>
        </div>
        </div>
    </nav>
    </div>
    <div class="header">
      <h1>Welcome To ChocoStock</h1>
    </div>
  
    <div class="container mt-4">
      <h3 id="jumlahitem"></h3>
  
      {% if messages %}
        {% for message in messages %}
          <h5>{{ message }}</h5>
        {% endfor %}
      {% endif %}

    <div id="product_container" class="row">
        <!-- Produk akan dimuat di sini -->
    </div>


    <div class="modal fade" id="addProductModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add New Product</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="form" onsubmit="return false;">
              {% csrf_token %}
              <div class="mb-3">
                <label for="productName" class="form-label">Product Name</label>
                <input type="text" class="form-control" id="productName" name="product_name" required>
              </div>
              <div class="mb-3">
                <label for="productBrand" class="form-label">Brand</label>
                <input type="text" class="form-control" id="productBrand" name="brand" required>
              </div>
              <div class="mb-3">
                <label for="productPrice" class="form-label">Price</label>
                <input type="text" class="form-control" id="productPrice" name="price" required>
              </div>
              <div class="mb-3">
                <label for="productDescription" class="form-label">Description</label>
                <textarea class="form-control" id="productDescription" name="description" required></textarea>
              </div>
              <div class="mb-3">
                <label for="productAmount" class="form-label">Amount</label>
                <input type="number" class="form-control" id="productAmount" name="amount" required>
              </div>
            </form>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
          </div>
      </div>
  </div>
</div>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addProductModal"  style="margin: 20px;" >Add Product by AJAX</button>
    <a href="{% url 'main:create_product' %}">
        <button type="button" class="btn btn-primary" style="margin: 20px;">Add New Product</button>
    </a>

    <h5 style="margin: 20px;">Sesi terakhir login: {{ last_login }}</h5>
    
    <br />
  

    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }


        async function refreshProducts() {
            const products = await getProducts();
            const productContainer = document.getElementById("product_container");

            // Hapus semua card produk yang ada
            productContainer.innerHTML = "";

            products.forEach((item) => {
                const productCard = document.createElement("div");
                productCard.className = "col-md-4 mb-4"; 
                const productCardInner = document.createElement("div");
                productCardInner.className = "card";

                productCardInner.innerHTML = `
                    <div class="card-body">
                        <h5 class="card-title">${item.fields.product_name}</h5>
                        <p class="card-text">Price: ${item.fields.price}</p>
                        <p class="card-text">Description: ${item.fields.description}</p>
                        <p class="card-text">Brand: ${item.fields.brand}</p>
                        <p class="card-text">Amount: 
                            <a href="remove_amount/${item.pk}" class="btn btn-danger">-</a> ${item.fields.amount}
                            <a href="add_amount/${item.pk}" class="btn btn-success">+</a>
                        </p>
                        <div class="d-flex justify-content-center">
                            <a href="delete_product/${item.pk}" class="btn btn-warning">Delete</a>
                            <a href="edit-product/${item.pk}" class="btn btn-info">Edit</a>
                        </div>
                    </div>
                `;

                productCard.appendChild(productCardInner);
                productContainer.appendChild(productCard);

               
            });
        const h3 = document.getElementById("jumlahitem")
        h3.innerHTML = ` Kamu menyimpan ${products.length} item pada aplikasi ini`
        }
  
        refreshProducts();
        function addProduct() {
          fetch("{% url 'main:create_ajax' %}", {
              method: "POST",
              body: new FormData(document.querySelector('#form'))
          }).then(refreshProducts)

          document.getElementById("form").reset()
          return false
      }
      document.getElementById("button_add").onclick = addProduct
    </script>

    

  {% endblock content %}
  

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
body {
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
}

    .register-container {
    color :#5d2a08;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.register-box {
    background-color: rgba(255, 253, 230, 0.8);
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
    max-width: 400px;
    margin: auto;
}

.register-box h1 {
    text-align: center;
    margin-bottom: 20px;
}

.register-form td {
    padding: 10px;
}

.form-control {
    width: calc(100% - 20px);
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

.register_btn {
    background-color: #5d2a08;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    width: 100%;
    font-size: 16px;
    align-items: center;
}

.register_btn:hover {
    background-color: #c38b60;
}

.register-form {
    margin-bottom: 20px;
}

</style>

<div class="register-container">
    <div class="register-box">
        <h1>Register</h1>

        <form method="POST">
            {% csrf_token %}
            <table class="register-form">
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input class="btn register_btn" type="submit" name="submit" value="Daftar" /></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>

{% endblock content %}